default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_bin
  pool: 150
  username: root
  password: apple123$
  host: 127.0.0.1
  reconnect: true

development:
  <<: *default
  database: top_pack_development
  password: apple123$

test: &test
  <<: *default
  database: top_pack_test

production:
  <<: *default
  database: top_pack_production
